
- name: "Install ZSH and change default shell"
  block:
  
  - name: "Install ZSH"
    community.general.homebrew:
      name:
        - 'zsh'

  - name: "Obtain the Path to ZSH"
    ansible.builtin.command: which zsh
    register: zsh_path
    changed_when: false

  - name: "change default shell to fish"
    become: true
    ansible.builtin.user:
      name: '{{ ansible_user }}'
      shell: '{{ zsh_path.stdout }}'
      system: true