
- name: "Install ZSH and Change Default Shell"
  block:
  
  - name: "Install ZSH"
    community.general.homebrew:
      name:
        - 'zsh'

  - name: "Obtain the Path to ZSH"
    ansible.builtin.command: which zsh
    register: zsh_path
    changed_when: false

  - name: "Change Default Shell to ZSH"
    become: true
    ansible.builtin.user:
      name: '{{ ansible_user }}'
      shell: '{{ zsh_path.stdout }}'