- name: "Install Alacritty (macOS)"
  when: ansible_os_family == "Darwin"
  block:

  - name: "Install Alacritty"
    community.general.homebrew_cask:
      name:
        - alacritty
      install_options: no-quarantine
      accept_external_apps: true



- name: "Install Alacritty (Linux)"
  when: ansible_os_family == "Debian"
  block:

  - name: Install Snapd
    become: true
    ansible.builtin.package:
      name: 
      - snapd

  - name: Install core snap
    become: true
    community.general.snap:
      name: core

  - name: Install Alacritty
    become: true
    community.general.snap:
      name: alacritty
      classic: true