- name: "Install Fonts (macOS)"
  when: ansible_os_family == "Darwin"
  block:
  
  - name: "Brew Tap homebrew/cask-fonts"
    community.general.homebrew_tap: 
      name: homebrew/cask-fonts
      state: present

  - name: "Install Fonts"
    community.general.homebrew_cask:
      name:
        - font-powerline-symbols
        - font-jetbrains-mono-nerd-font
      install_options: no-quarantine
      accept_external_apps: true



- name: "Install Fonts (Linux)"
  when: ansible_os_family == "Debian"
  block:

    - name: Ensure fonts directory
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.fonts"
        state: directory
        mode: "0755"
        owner: "{{ ansible_user }}"

    - name: Check if JetBrains Mono font is present
      ansible.builtin.stat:
        path: "{{ ansible_user }}/.local/share/fonts/JetBrainsMonoNerd*FontMono*"
      register: jetbrains_mono_present

    - name: Download Jetbrains Mono if not present
      when: not jetbrains_mono_present.stat.exists
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip
        dest: "{{ ansible_user_dir }}/.local/share/fonts/"
        remote_src: true
        mode: "0755"
        owner: "{{ ansible_user }}"
